default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: mars_curiosity_development

test:
  <<: *default
  database: mars_curiosity_test

production:
  <<: *default
  database: mars_curiosity_production
