development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: mars_curiosity_development
  password: <%= ENV["RAILS_DB_PASSWORD"] %>

test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: mars_curiosity_test
  password: <%= ENV["RAILS_DB_PASSWORD"] %>

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: mars_curiosity_production
