default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: mars_curiosity_development
  password: <%= ENV["RAILS_DB_PASSWORD"] %>

test:
  <<: *default
  database: mars_curiosity_test
  password: <%= ENV["RAILS_DB_PASSWORD"] %>

production:
  <<: *default
  database: mars_curiosity_production
